#!/usr/bin/env bash

alias cnpm="npm --registry=https://registry.npm.taobao.org \
    --cache=$HOME/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$HOME/.cnpmrc"

alias py2="source $HOME/venv/venv2/bin/activate"
alias py3="source $HOME/venv/venv3/bin/activate"
alias pyd="deactivate"

# qccr
alias cr="source $HOME/qccr/crywgl/venv/bin/activate"
alias tk="source $HOME/qccr/tkeeper/venv/bin/activate"
alias tc="source $HOME/qccr/tconfig/venv/bin/activate"

# Google Chrome
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# mysql
alias mysql-start="/usr/local/mysql/support-files/mysql.server start"
alias mysql-stop="/usr/local/mysql/support-files/mysql.server stop"
alias mysql-restart="/usr/local/mysql/support-files/mysql.server restart"
alias mysql-force="pkill -9 mysql"

# redis
alias redis-start="/usr/local/redis/src/redis-server /usr/local/redis/redis.conf"
alias redis-stop="pkill -9 redis"

# Shortcuts
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias g="git"
alias ..="cd .."

alias fpy="cd /usr/local/Frameworks/Python.framework/Versions/"
