#!/usr/bin/env bash

# Google Chrome
alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# Shortcuts
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias g="git"
alias ..="cd .."

# cheat

alias lsl="ls -lrt"
alias lm="ls -al|more"
alias vi="vim"
alias pyd="deactivate"

# python catalogue
alias fpy="cd /usr/local/Frameworks/Python.framework/Versions/"

